# Generated by Django 5.0.6 on 2026-07-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationround',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='negotiationround',
            name='round_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiationround',
            name='side',
            field=models.CharField(choices=[('Our offer', 'Our offer'), ('Customer ask', 'Customer ask')], default='Our offer', max_length=20),
        ),
        migrations.AddField(
            model_name='negotiationround',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Countered', 'Countered')], default='Open', max_length=15),
        ),
    ]
