# Generated by Django 5.0.6 on 2026-07-04 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_negotiationround_discount_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('Price', 'Price'), ('Timing', 'Timing'), ('Competitor', 'Competitor'), ('No budget', 'No budget'), ('No response', 'No response'), ('Other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='decision_maker_present',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outcome_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='outcome_sentiment',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=10),
        ),
        migrations.AddField(
            model_name='proposal',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='proposals/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='file_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='touchpoint',
            name='channel',
            field=models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Email', 'Email'), ('Note', 'Note'), ('Meeting', 'Meeting')], default='Call', max_length=15),
        ),
    ]
