# Generated by Django 5.0.6 on 2026-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_followup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Qualified', 'Qualified'), ('Meeting Scheduled', 'Meeting Scheduled'), ('Meeting Done', 'Meeting Done'), ('Proposal Sent', 'Proposal Sent'), ('Negotiation', 'Negotiation'), ('Won', 'Won'), ('Lost', 'Lost')], default='Enquiry', max_length=30),
        ),
    ]
