# Generated by Django 5.0.6 on 2026-07-07 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='lost_reason',
            field=models.CharField(blank=True, choices=[('Price', 'Price'), ('Timing', 'Timing'), ('Competitor', 'Competitor'), ('No budget', 'No budget'), ('No response', 'No response'), ('Feature gap', 'Feature gap'), ('Went in-house', 'Went in-house'), ('Other', 'Other')], max_length=20),
        ),
    ]
