# Generated by Django 5.0.6 on 2026-07-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_enquiry_lost_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchpoint',
            name='channel',
            field=models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Email', 'Email'), ('Note', 'Note'), ('Meeting', 'Meeting'), ('Negotiation', 'Negotiation')], default='Call', max_length=15),
        ),
    ]
