# Generated by Django 5.0.6 on 2026-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_touchpoint_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='touchpoint',
            name='direction',
            field=models.CharField(blank=True, choices=[('Outbound', 'Outbound'), ('Inbound', 'Inbound')], max_length=8),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='duration_sec',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=6),
        ),
        migrations.AddField(
            model_name='touchpoint',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
