# Generated by Django 5.0.6 on 2026-07-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_touchpoint_direction_touchpoint_duration_sec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='solution_type',
            field=models.CharField(blank=True, choices=[('SalesPort (DMS + SFA)', 'SalesPort (DMS + SFA)'), ('Supply Chain Management', 'Supply Chain Management'), ('Procurement Management', 'Procurement Management'), ('Livestock Management', 'Livestock Management'), ('Inventory Management', 'Inventory Management'), ('Production Management', 'Production Management'), ('Accounts Management', 'Accounts Management'), ('HR Management', 'HR Management'), ('Institute Management & Resource Optimization', 'Institute Management & Resource Optimization'), ('Other', 'Other')], max_length=60),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='solution_type_other',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
