# Generated by Django 5.0.6 on 2026-07-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_enquiry_solution_type_enquiry_solution_type_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='email_subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meeting',
            name='reschedule_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='meeting',
            name='whatsapp_message',
            field=models.TextField(blank=True),
        ),
    ]
