# Generated by Django 5.0.6 on 2026-07-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_meeting_email_body_meeting_email_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('founder', 'Founder'), ('sales_head', 'Sales Head'), ('consultant', 'Consultant')], default='consultant', max_length=20),
        ),
    ]
