# Generated by Django 5.0.6 on 2026-07-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Won', 'Won'), ('Lost', 'Lost'), ('Spam', 'Spam')], default='New', max_length=30),
        ),
    ]
