# Generated by Django 5.0.6 on 2026-07-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_reband_expected_value_wider_above_15l'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touchpoint',
            name='channel',
            field=models.CharField(choices=[('Call', 'Call'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Email', 'Email'), ('Note', 'Note'), ('Meeting', 'Meeting'), ('Negotiation', 'Negotiation'), ('Created', 'Created')], default='Call', max_length=15),
        ),
    ]
