# Generated by Django 5.0.6 on 2026-07-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_add_created_touchpoint_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('dlt_template_id', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='ntype',
            field=models.CharField(choices=[('pending_approval', 'Pending approval'), ('discrepancy', 'Discrepancy'), ('new_enquiry', 'New enquiry'), ('overdue', 'Overdue follow-up'), ('proposal_opened', 'Proposal opened'), ('meeting_reminder', 'Meeting reminder'), ('deal_won', 'Deal won'), ('status_changed', 'Status changed'), ('team_update', 'Activity update')], default='new_enquiry', max_length=25),
        ),
    ]
